### ISSUE TITLE
Additions from zaiste.net post

### ISSUE THREAD

**Issue by jtagcat** [ibraheemdev/modern-unix#37] opened 2021-07-04 17:15 UTC
https://zaiste.net/posts/shell-commands-rust

 - ~https://github.com/polyverse/rmesg — dmesg in rust~
 - ~https://github.com/dbrgn/tealdeer — tldr in rust~
 - https://github.com/pemistahl/grex — „A command-line tool and library for generating regular expressions from user-provided test cases.“
 - https://github.com/imsnif/bandwhich — top for bw
 
Thoughts?

**Comment by ibraheemdev** [comment] 2021-07-21 00:09
Dupe of #11.

**Closed by ibraheemdev** 2021-07-21 00:09 UTC
