### ISSUE TITLE
Proposal: Helix

### ISSUE THREAD

**Issue by nuke-web3** [ibraheemdev/modern-unix#121] opened 2023-06-07 14:30 UTC
(based on https://github.com/ibraheemdev/modern-unix/issues/104#issuecomment-1580945634) 

https://github.com/helix-editor/helix

**Comment by TheTedAdams** [comment] 2023-08-24 20:50
Duplicate of #35 ?

**Comment by NukeManDan** [comment] 2023-08-24 22:53
Kinda - this isn't a _replacement_ for `vim` but an _alternative_ in the same "family". So I think the proposal isn't quite a dup.

**Comment by ibraheemdev** [comment] 2024-09-10 19:48
Sorry, don't really want to get into text editors on this list :)

**Closed by ibraheemdev** 2024-09-10 19:48 UTC
